export const PAGINATION = {
    DEFAULT_PAGE: 1,
    DEFAULT_PAGE_SIZE: 5,
    MAX_PAGE_SIZE: 100,
    MIN_PAGE_SIZE: 1

}

export const USAGE_LIMITS = {
  FREE_MONTHLY_RUNS: 200,
  PRO_MONTHLY_RUNS: 2000,
  FREE_AUDIT_RETENTION_DAYS: 90,
  PRO_AUDIT_RETENTION_DAYS: 365,
} as const;